const Joi = require('joi');

const UserPayloadSchema = Joi.object({
  name: Joi.string().min(3).required(),
  email: Joi.string().email().required(),
  password: Joi.string().min(8).required(),
  hobby: Joi.string().valid(
    "berselancar",
        "paralayang",
        "bermain catur",
        "mencoba kuliner baru",
        "bermain skateboard",
        "menyelam",
        "mengikuti cosplay",
        "merakit model kit",
        "mengajar online",
        "menulis skenario",
        "merakit robot",
        "bermain catur kilat",
        "mengoleksi figur action",
        "merakit drone",
        "bermain musik",
        "menonton teater",
        "membuat komik",
        "menjadi relawan sosial",
        "membaca buku",
        "bermain bulu tangkis",
        "menulis puisi",
        "bermain biola",
        "fotografi",
        "mempelajari astronomi",
        "bermain puzzle",
        "coding",
        "bermain peran di drama",
        "menjelajahi gua",
        "menanam tanaman",
        "panjat tebing",
        "menyanyi",
        "belajar bahasa asing",
        "menulis cerita",
        "bermain origami",
        "menjahit",
        "berburu",
        "berenang",
        "membuat podcast",
        "membuat lagu",
        "menari",
        "mengikuti perlombaan menulis",
        "bermain trampolin",
        "berlatih yoga",
        "melukis",
        "mendaki gunung",
        "menggambar digital",
        "bermain biliar",
        "bermain drum",
        "bermain sepak bola",
        "mengembangkan aplikasi",
        "berlatih bela diri tradisional",
        "mendengarkan podcast",
        "berlatih beatbox",
        "mengikuti maraton",
        "bermain voli",
        "bermain role-playing game",
        "bermain kendama",
        "mengoleksi koin",
        "menonton anime",
        "menjadi kolektor barang antik",
        "merancang pakaian",
        "mengedit video",
        "bermain basket",
        "bermain piano",
        "berlatih bela diri",
        "bermain game",
        "menonton film",
        "bermain kartu",
        "bermain boomerang",
        "menulis jurnal harian",
        "berlatih sulap kartu",
        "menjadi reviewer teknologi",
        "mencoba seni kaligrafi",
        "bermain sulap",
        "bermain tenis",
        "merajut",
        "bermain paintball",
        "bermain e-sports",
        "bersepeda",
        "bermain airsoft gun",
        "mengedit foto",
        "menulis blog",
        "membuat film pendek",
        "menulis lirik lagu",
        "memancing",
        "menggambar",
        "merajut tas",
        "merakit elektronik",
        "memasak",
        "bermain roller skating",
        "merakit komputer",
        "bermain gitar",
        "bermain harmonika",
        "membaca novel misteri",
        "berkemah",
        "mengoleksi perangko",
        "bermain golf",
        "mengikuti lomba lari",
        "berlatih parkour",
        "bermain frisbee"
  ).required(),
  age: Joi.number().integer().min(12).max(100).required(),
  occupation: Joi.string().valid(
        "Fisioterapis",
        "Ahli Lingkungan",
        "Penyiar Radio",
        "Jaksa",
        "IT Support",
        "Arsitek Lanskap",
        "Blogger",
        "Hakim",
        "Pramugari",
        "Reporter",
        "Peneliti",
        "Desainer",
        "Pelatih Olahraga",
        "Dokter",
        "Jurnalis",
        "Ilmuwan",
        "Software Engineer",
        "Polisi",
        "Makeup Artist",
        "Ahli Gizi",
        "Penata Rambut",
        "Masinis",
        "Pelaut",
        "Mahasiswa",
        "HRD",
        "Fotografer",
        "Apoteker",
        "Ekonom",
        "Teknisi Mesin",
        "Penasihat Pajak",
        "Penyanyi",
        "Arkeolog",
        "Model",
        "Sejarawan",
        "Marketing",
        "Penasihat Hukum",
        "Voice Over",
        "Mekanik",
        "Game Developer",
        "Ahli Kimia",
        "Koki",
        "Tukang Kayu",
        "Teknisi Elektronik",
        "Rekruter",
        "Montir",
        "Videografer",
        "Akuntan",
        "Arsitek",
        "Pakar Keuangan",
        "Pilot",
        "Aktor",
        "Ahli Kecerdasan Buatan",
        "Operator Produksi",
        "Pengacara",
        "Animator",
        "Surveyor",
        "Ahli Robotika",
        "Petani",
        "Cyber Security",
        "Meteorolog",
        "Pustakawan",
        "Penjaga Hutan",
        "MC",
        "Perawat",
        "Pemandu Wisata",
        "Antropolog",
        "Wasit",
        "DevOps Engineer",
        "Analis Saham",
        "Analis Data",
        "Produser Film",
        "Editor",
        "Atlet",
        "Sopir",
        "Seniman",
        "Lainnya",
        "Teknisi Medis",
        "Dosen",
        "Nelayan",
        "Penulis",
        "Network Engineer",
        "Tentara",
        "Psikolog",
        "Wirausahawan",
        "Komedian",
        "Desainer Interior",
        "Ahli Biologi",
        "Bankir",
        "Astronom",
        "Investor",
        "Ahli Konservasi",
        "Musisi",
        "Content Creator",
        "Podcaster",
        "Administrator Database",
        "Ahli Statistik",
        "Event Organizer",
        "Tukang Las",
        "Sutradara",
        "Geolog",
        "Urban Planner",
        "Peternak",
        "Manajer Proyek",
        "Influencer",
        "Teknisi Laboratorium",
        "Guru",
  ).required(),
  marital_status: Joi.string().valid('Menikah', 'Belum Menikah').required(),
  role: Joi.string().valid('user', 'admin').default('user')
});

const UserUpdateSchema = Joi.object({
  name: Joi.string().min(3),
  email: Joi.string().email(),
  password: Joi.string().min(8),
  hobby: Joi.string().valid(
        "berselancar",
        "paralayang",
        "bermain catur",
        "mencoba kuliner baru",
        "bermain skateboard",
        "menyelam",
        "mengikuti cosplay",
        "merakit model kit",
        "mengajar online",
        "menulis skenario",
        "merakit robot",
        "bermain catur kilat",
        "mengoleksi figur action",
        "merakit drone",
        "bermain musik",
        "menonton teater",
        "membuat komik",
        "menjadi relawan sosial",
        "membaca buku",
        "bermain bulu tangkis",
        "menulis puisi",
        "bermain biola",
        "fotografi",
        "mempelajari astronomi",
        "bermain puzzle",
        "coding",
        "bermain peran di drama",
        "menjelajahi gua",
        "menanam tanaman",
        "panjat tebing",
        "menyanyi",
        "belajar bahasa asing",
        "menulis cerita",
        "bermain origami",
        "menjahit",
        "berburu",
        "berenang",
        "membuat podcast",
        "membuat lagu",
        "menari",
        "mengikuti perlombaan menulis",
        "bermain trampolin",
        "berlatih yoga",
        "melukis",
        "mendaki gunung",
        "menggambar digital",
        "bermain biliar",
        "bermain drum",
        "bermain sepak bola",
        "mengembangkan aplikasi",
        "berlatih bela diri tradisional",
        "mendengarkan podcast",
        "berlatih beatbox",
        "mengikuti maraton",
        "bermain voli",
        "bermain role-playing game",
        "bermain kendama",
        "mengoleksi koin",
        "menonton anime",
        "menjadi kolektor barang antik",
        "merancang pakaian",
        "mengedit video",
        "bermain basket",
        "bermain piano",
        "berlatih bela diri",
        "bermain game",
        "menonton film",
        "bermain kartu",
        "bermain boomerang",
        "menulis jurnal harian",
        "berlatih sulap kartu",
        "menjadi reviewer teknologi",
        "mencoba seni kaligrafi",
        "bermain sulap",
        "bermain tenis",
        "merajut",
        "bermain paintball",
        "bermain e-sports",
        "bersepeda",
        "bermain airsoft gun",
        "mengedit foto",
        "menulis blog",
        "membuat film pendek",
        "menulis lirik lagu",
        "memancing",
        "menggambar",
        "merajut tas",
        "merakit elektronik",
        "memasak",
        "bermain roller skating",
        "merakit komputer",
        "bermain gitar",
        "bermain harmonika",
        "membaca novel misteri",
        "berkemah",
        "mengoleksi perangko",
        "bermain golf",
        "mengikuti lomba lari",
        "berlatih parkour",
        "bermain frisbee"
  ),
  age: Joi.number().integer().min(15).max(70),
  occupation: Joi.string().valid(
        "Fisioterapis",
        "Ahli Lingkungan",
        "Penyiar Radio",
        "Jaksa",
        "IT Support",
        "Arsitek Lanskap",
        "Blogger",
        "Hakim",
        "Pramugari",
        "Reporter",
        "Peneliti",
        "Desainer",
        "Pelatih Olahraga",
        "Dokter",
        "Jurnalis",
        "Ilmuwan",
        "Software Engineer",
        "Polisi",
        "Makeup Artist",
        "Ahli Gizi",
        "Penata Rambut",
        "Masinis",
        "Pelaut",
        "Mahasiswa",
        "HRD",
        "Fotografer",
        "Apoteker",
        "Ekonom",
        "Teknisi Mesin",
        "Penasihat Pajak",
        "Penyanyi",
        "Arkeolog",
        "Model",
        "Sejarawan",
        "Marketing",
        "Penasihat Hukum",
        "Voice Over",
        "Mekanik",
        "Game Developer",
        "Ahli Kimia",
        "Koki",
        "Tukang Kayu",
        "Teknisi Elektronik",
        "Rekruter",
        "Montir",
        "Videografer",
        "Akuntan",
        "Arsitek",
        "Pakar Keuangan",
        "Pilot",
        "Aktor",
        "Ahli Kecerdasan Buatan",
        "Operator Produksi",
        "Pengacara",
        "Animator",
        "Surveyor",
        "Ahli Robotika",
        "Petani",
        "Cyber Security",
        "Meteorolog",
        "Pustakawan",
        "Penjaga Hutan",
        "MC",
        "Perawat",
        "Pemandu Wisata",
        "Antropolog",
        "Wasit",
        "DevOps Engineer",
        "Analis Saham",
        "Analis Data",
        "Produser Film",
        "Editor",
        "Atlet",
        "Sopir",
        "Seniman",
        "Lainnya",
        "Teknisi Medis",
        "Dosen",
        "Nelayan",
        "Penulis",
        "Network Engineer",
        "Tentara",
        "Psikolog",
        "Wirausahawan",
        "Komedian",
        "Desainer Interior",
        "Ahli Biologi",
        "Bankir",
        "Astronom",
        "Investor",
        "Ahli Konservasi",
        "Musisi",
        "Content Creator",
        "Podcaster",
        "Administrator Database",
        "Ahli Statistik",
        "Event Organizer",
        "Tukang Las",
        "Sutradara",
        "Geolog",
        "Urban Planner",
        "Peternak",
        "Manajer Proyek",
        "Influencer",
        "Teknisi Laboratorium",
        "Guru",
  ),
  marital_status: Joi.string().valid('Menikah', 'Belum Menikah'),
  role: Joi.string().valid('user', 'admin')
});

const UserPasswordUpdateSchema = Joi.object({
  oldPassword: Joi.string().min(8).required(),
  newPassword: Joi.string().min(8).required(),
});

module.exports = { UserPayloadSchema, UserUpdateSchema, UserPasswordUpdateSchema };
